# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/giuliabenvenuto/Documents/GitHub/SSGD_Problem/libs/geometry-central/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/giuliabenvenuto/Documents/GitHub/SSGD_Problem/libs/geometry-central/cmake/FindEigen3.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/giuliabenvenuto/Documents/GitHub/SSGD_Problem/libs/geometry-central/cmake/FindSuiteSparse.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/giuliabenvenuto/Documents/GitHub/SSGD_Problem/libs/geometry-central/cmake/UpdateCacheVariable.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/giuliabenvenuto/Documents/GitHub/SSGD_Problem/libs/geometry-central/deps/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/giuliabenvenuto/Documents/GitHub/SSGD_Problem/libs/geometry-central/src/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.28.3/share/cmake/Modules/CheckCSourceCompiles.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.28.3/share/cmake/Modules/CheckFunctionExists.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.28.3/share/cmake/Modules/CheckIncludeFile.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.28.3/share/cmake/Modules/CheckLibraryExists.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.28.3/share/cmake/Modules/FindBLAS.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.28.3/share/cmake/Modules/FindLAPACK.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.28.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.28.3/share/cmake/Modules/FindPackageMessage.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.28.3/share/cmake/Modules/FindThreads.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/eigen3/cmake/Eigen3Config.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/eigen3/cmake/Eigen3ConfigVersion.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/eigen3/cmake/Eigen3Targets.cmake))

/Users/giuliabenvenuto/Documents/GitHub/SSGD_Problem/build_xcode/CMakeFiles/cmake.check_cache: $(TARGETS)
	/opt/homebrew/Cellar/cmake/3.28.3/bin/cmake -S/Users/giuliabenvenuto/Documents/GitHub/SSGD_Problem -B/Users/giuliabenvenuto/Documents/GitHub/SSGD_Problem/build_xcode
